proxy:
#  build: ./proxy
  build: ./java-proxy
  ports:
#  - "3000:3000"
  - "3000:8080"
  links:
  - redis
  - coder
  env_file:
    - ./erasure.env

redis:
  image: redis

coder:
  build: ./pycoder
  env_file:
    - ./erasure.env
